# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

    binlist.api.retry-delay-seconds: 2
    binlist.api.cache-lifetime-seconds: 1

    exchangerates.api.cache-lifetime-seconds: 1


services:

    #TODO: might be nice to mock services and pass mocked responses as fixtures
#    App\Service\BinlistReader\BinlistReader:
#        class: App\Service\BinlistReader\MockBinlistReader
#
#    App\Service\ExchangeRateReader\ExchangeRateReader:
#        class: App\Service\ExchangeRateReader\MockExchangeRateReader


